language: erlang
otp_release:
   - 17.1
   - 17.0
   - R16B03-1
   - R16B03
   - R16B02
   - R16B01
   - R15B03
   - R15B02
   - R15B01

script:
   - "wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3"
   - "./rebar3 do compile, dialyzer, ct, eunit"
